

DROP DATABASE IF EXISTS tienda;
CREATE DATABASE tienda CHARACTER SET utf8mb4;
USE tienda;

CREATE TABLE fabricante (
  codigo INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL
);

CREATE TABLE producto (
  codigo INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  precio DOUBLE NOT NULL,
  codigo_fabricante INT UNSIGNED NOT NULL,
  FOREIGN KEY (codigo_fabricante) REFERENCES fabricante(codigo)
);

INSERT INTO fabricante VALUES(1, 'Asus');
INSERT INTO fabricante VALUES(2, 'Lenovo');
INSERT INTO fabricante VALUES(3, 'Hewlett-Packard');
INSERT INTO fabricante VALUES(4, 'Samsung');
INSERT INTO fabricante VALUES(5, 'Seagate');
INSERT INTO fabricante VALUES(6, 'Crucial');
INSERT INTO fabricante VALUES(7, 'Gigabyte');
INSERT INTO fabricante VALUES(8, 'Huawei');
INSERT INTO fabricante VALUES(9, 'Xiaomi');

INSERT INTO producto VALUES(1, 'Disco duro SATA3 1TB', 86.99, 5);
INSERT INTO producto VALUES(2, 'Memoria RAM DDR4 8GB', 120, 6);
INSERT INTO producto VALUES(3, 'Disco SSD 1 TB', 150.99, 4);
INSERT INTO producto VALUES(4, 'GeForce GTX 1050Ti', 185, 7);
INSERT INTO producto VALUES(5, 'GeForce GTX 1080 Xtreme', 755, 6);
INSERT INTO producto VALUES(6, 'Monitor 24 LED Full HD', 202, 1);
INSERT INTO producto VALUES(7, 'Monitor 27 LED Full HD', 245.99, 1);
INSERT INTO producto VALUES(8, 'Portátil Yoga 520', 559, 2);
INSERT INTO producto VALUES(9, 'Portátil Ideapd 320', 444, 2);
INSERT INTO producto VALUES(10, 'Impresora HP Deskjet 3720', 59.99, 3);
INSERT INTO producto VALUES(11, 'Impresora HP Laserjet Pro M26nw', 180, 3);



SELECT producto.nombre FROM producto;

SELECT producto.nombre, producto.precio FROM producto;

SELECT * FROM PRODUCTO;

SELECT PRODUCTO.NOMBRE, PRODUCTO.PRECIO, PRODUCTO.PRECIO * 1.07 FROM producto;

SELECT PRODUCTO.NOMBRE AS NOM_DE_PRODUCTO, PRODUCTO.PRECIO AS EUROS, PRODUCTO.PRECIO * 1.07 AS DOLARS FROM producto;

SELECT UPPER(producto.nombre), producto.precio FROM producto;

SELECT LOWER(producto.nombre), producto.precio FROM producto;

SELECT NOMBRE, UPPER(LEFT(NOMBRE, 2))  FROM fabricante;

SELECT producto.nombre, round(producto.precio) FROM producto;

SELECT producto.nombre, TRUNCATE(producto.precio, 0) FROM producto;

SELECT fabricante.codigo FROM PRODUCTO INNER JOIN FABRICANTE ON PRODUCTO.codigo_fabricante = FABRICANTE.CODIGO;

SELECT DISTINCTROW FABRICANTE.codigo FROM producto INNER JOIN fabricante ON PRODUCTO.codigo_fabricante = FABRICANTE.CODIGO;

SELECT nombre FROM fabricante order by nombre asc;

SELECT nombre FROM fabricante order by nombre desc;

SELECT nombre FROM producto order by nombre asc, precio desc;

SELECT * FROM FABRICANTE LIMIT 5;

SELECT * FROM FABRICANTE LIMIT 2 OFFSET 3;

SELECT NOMBRE, PRECIO FROM PRODUCTO ORDER BY PRECIO ASC LIMIT 1;

SELECT NOMBRE, PRECIO FROM PRODUCTO ORDER BY PRECIO DESC LIMIT 1;

SELECT PRODUCTO.NOMBRE FROM PRODUCTO INNER JOIN FABRICANTE ON FABRICANTE.codigo = PRODUCTO.codigo_fabricante WHERE FABRICANTE.CODIGO = 2;

SELECT PRODUCTO.NOMBRE, PRODUCTO.PRECIO, FABRICANTE.NOMBRE FROM PRODUCTO INNER JOIN FABRICANTE ON FABRICANTE.codigo = PRODUCTO.codigo_fabricante;

SELECT PRODUCTO.NOMBRE, PRODUCTO.PRECIO, FABRICANTE.NOMBRE FROM PRODUCTO INNER JOIN FABRICANTE ON FABRICANTE.codigo = PRODUCTO.codigo_fabricante ORDER BY FABRICANTE.NOMBRE ASC;

SELECT PRODUCTO.CODIGO, PRODUCTO.NOMBRE, FABRICANTE.* FROM PRODUCTO INNER JOIN FABRICANTE ON FABRICANTE.codigo = PRODUCTO.codigo_fabricante;

SELECT PRODUCTO.NOMBRE, PRODUCTO.PRECIO, FABRICANTE.NOMBRE FROM PRODUCTO INNER JOIN FABRICANTE ON FABRICANTE.codigo = PRODUCTO.codigo_fabricante ORDER BY PRECIO ASC LIMIT 1;

SELECT PRODUCTO.NOMBRE, PRODUCTO.PRECIO, FABRICANTE.NOMBRE FROM PRODUCTO INNER JOIN FABRICANTE ON FABRICANTE.codigo = PRODUCTO.codigo_fabricante ORDER BY PRECIO DESC LIMIT 1;

 SELECT PRODUCTO.NOMBRE FROM PRODUCTO INNER JOIN FABRICANTE ON PRODUCTO.codigo_fabricante = FABRICANTE.CODIGO WHERE FABRICANTE.nombre = 'Lenovo';

 SELECT PRODUCTO.NOMBRE, producto.precio FROM PRODUCTO INNER JOIN FABRICANTE ON PRODUCTO.codigo_fabricante = FABRICANTE.CODIGO WHERE FABRICANTE.nombre = 'Crucial';

 SELECT PRODUCTO.NOMBRE FROM PRODUCTO INNER JOIN FABRICANTE ON PRODUCTO.codigo_fabricante = FABRICANTE.CODIGO WHERE `precio` > 200 AND  FABRICANTE.nombre = 'Crucial';

SELECT PRODUCTO.NOMBRE, fabricante.nombre FROM PRODUCTO INNER JOIN FABRICANTE ON PRODUCTO.codigo_fabricante = FABRICANTE.CODIGO where fabricante.nombre = 'Asus' or fabricante.nombre = 'Hewlett-Packard' or fabricante.nombre = 'Seagate';

SELECT PRODUCTO.NOMBRE, fabricante.nombre FROM PRODUCTO INNER JOIN FABRICANTE ON PRODUCTO.codigo_fabricante = FABRICANTE.CODIGO where fabricante.nombre IN ('Asus', 'Hewlett-Packard', 'Seagate');

SELECT PRODUCTO.NOMBRE, PRODUCTO.PRECIO FROM PRODUCTO INNER JOIN FABRICANTE ON FABRICANTE.codigo = PRODUCTO.codigo_fabricante WHERE FABRICANTE.NOMBRE LIKE '%e';

SELECT PRODUCTO.NOMBRE, PRODUCTO.PRECIO FROM PRODUCTO INNER JOIN FABRICANTE ON FABRICANTE.codigo = PRODUCTO.codigo_fabricante WHERE FABRICANTE.NOMBRE LIKE '%w%';

SELECT PRODUCTO.NOMBRE, PRODUCTO.PRECIO, FABRICANTE.NOMBRE FROM PRODUCTO INNER JOIN FABRICANTE ON FABRICANTE.codigo = PRODUCTO.codigo_fabricante WHERE PRECIO >= 180 ORDER BY PRECIO DESC, PRODUCTO.NOMBRE ASC;

SELECT DISTINCTROW FABRICANTE.* FROM FABRICANTE INNER JOIN PRODUCTO ON PRODUCTO.codigo_fabricante = FABRICANTE.codigo;

SELECT FABRICANTE.NOMBRE, PRODUCTO.NOMBRE FROM FABRICANTE LEFT JOIN PRODUCTO ON FABRICANTE.CODIGO = PRODUCTO.codigo_fabricante;

SELECT FABRICANTE.NOMBRE, PRODUCTO.NOMBRE FROM FABRICANTE LEFT JOIN PRODUCTO ON FABRICANTE.CODIGO = PRODUCTO.codigo_fabricante WHERE PRODUCTO.NOMBRE IS NULL;

SELECT producto.nombre FROM PRODUCTO WHERE PRODUCTO.codigo_fabricante = (SELECT FABRICANTE.CODIGO FROM FABRICANTE WHERE FABRICANTE.NOMBRE = 'Lenovo' );

SELECT * FROM producto where producto.precio >= (SELECT max(producto.precio) FROM producto where (SELECT FABRICANTE.CODIGO FROM FABRICANTE WHERE FABRICANTE.NOMBRE = 'Lenovo' ));

SELECT FABRICANTE.NOMBRE, PRODUCTO.NOMBRE, producto.precio FROM FABRICANTE LEFT JOIN PRODUCTO ON FABRICANTE.CODIGO = PRODUCTO.codigo_fabricante WHERE FABRICANTE.NOMBRE = 'Lenovo' order by producto.precio desc limit 1;

SELECT FABRICANTE.NOMBRE, PRODUCTO.NOMBRE, producto.precio FROM FABRICANTE LEFT JOIN PRODUCTO ON FABRICANTE.CODIGO = PRODUCTO.codigo_fabricante WHERE FABRICANTE.NOMBRE = 'Hewlett-Packard' order by producto.precio asc limit 1;

