DROP DATABASE IF EXISTS YOUTUBE_DANI;

CREATE DATABASE YOUTUBE_DANI;

USE YOUTUBE_DANI;

CREATE TABLE USUARIO(
    ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    EMAIL VARCHAR (30),
    PASWORD VARCHAR (6), 
    NOMBRE VARCHAR (20),
    FECHA_NACIMIENTO DATE,
    SEXO CHAR,
    PAIS VARCHAR (20),
    CODIGO_POSTAL INT (10)
);

CREATE TABLE ESTADO_VIDEO(
    ID_ESTADO_VIDEO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_ESTADO VARCHAR (20)
);


CREATE TABLE VIDEO(
    ID_VIDEO INT PRIMARY KEY AUTO_INCREMENT,
    TITULO VARCHAR (30) NOT NULL,
    DESCRIPCION VARCHAR (100),
    TAMAÑO_ARCHIVO DEC (10.2),
    DURACION TIME,
    THUMBNAIL LONGBLOB NULL,
    NUMERO_REPRODUCCIONES INT (10),
    NUMERO_LIKES INT (10),
    NUMERO_DISLIKES INT (10),
    ESTADO INT (5),
    USUARIO INT (5),
    FECHA_PUBLICACION DATETIME,
    FOREIGN KEY (ESTADO) REFERENCES ESTADO_VIDEO (ID_ESTADO_VIDEO),
    FOREIGN KEY (USUARIO) REFERENCES USUARIO (ID_USUARIO)
);

CREATE TABLE ETIQUETA_VIDEO(
    ID_ETIQUETA_VIDEO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_ETIQUETA VARCHAR (20),
    ID_VIDEO INT (5) NOT NULL,
    ID_USUARIO INT (5) NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO),
    FOREIGN KEY (ID_VIDEO) REFERENCES VIDEO (ID_VIDEO)
);

CREATE TABLE LIKE_VIDEO(
    ID_LIKE INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT (5) NOT NULL ,
    ID_VIDEO INT (5) NOT NULL  ,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO),
    FOREIGN KEY (ID_VIDEO) REFERENCES VIDEO (ID_VIDEO)
); 

CREATE TABLE DISLIKE_VIDEO(
    ID_DISLIKE INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT (5) NOT NULL ,
    ID_VIDEO INT (5) NOT NULL ,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO),
    FOREIGN KEY (ID_VIDEO) REFERENCES VIDEO (ID_VIDEO)
); 


CREATE TABLE CANAL(
    ID_CANAL INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR (20),
    DESCRIPCION VARCHAR (100),
    FECHA_CREACION DATETIME,
    ID_USUARIO INT (5) NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);

CREATE TABLE SUSCRIPCION_DE_CANAL(
    ID_SUSCRIPCION INT PRIMARY KEY AUTO_INCREMENT,
    ID_CANAL INT (5) NOT NULL,
    ID_USUARIO INT (5) NOT NULL,
    FOREIGN KEY (ID_CANAL) REFERENCES CANAL (ID_CANAL),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);

CREATE TABLE COMENTARIO(
    ID_COMENTARIO INT PRIMARY KEY AUTO_INCREMENT,
    COMENTARIO VARCHAR (100),
    FECHA DATE,
    ID_VIDEO INT (5) NOT NULL,
    ID_USUARIO INT (5) NOT NULL,
    FOREIGN KEY (ID_VIDEO) REFERENCES VIDEO (ID_VIDEO),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);

CREATE TABLE LIKE_COMENTARIO(
    ID_LIKE INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT (5) NOT NULL ,
    ID_COMENTARIO INT (5) NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO),
    FOREIGN KEY (ID_COMENTARIO) REFERENCES COMENTARIO (ID_COMENTARIO)
); 

CREATE TABLE DISLIKE_COMENTARIO(
    ID_DISLIKE INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT (5) NOT NULL,
    ID_COMENTARIO INT (5) NULL ,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO),
    FOREIGN KEY (ID_COMENTARIO) REFERENCES COMENTARIO (ID_COMENTARIO)
); 

CREATE TABLE PLAYLIST(
    ID_PLAYLIST INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT (5) NOT NULL,
    ID_ESTADO INT (5) NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO),
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO_VIDEO (ID_ESTADO_VIDEO)
);

CREATE TABLE VIDEOS_PLAYLIST(
    ID_PLAYLIST INT (5) NOT NULL,
    ID_VIDEO INT (5) NOT NULL,
    FOREIGN KEY (ID_PLAYLIST) REFERENCES PLAYLIST (ID_PLAYLIST),
    FOREIGN KEY (ID_VIDEO) REFERENCES VIDEO (ID_VIDEO)
);

INSERT INTO USUARIO (EMAIL, PASWORD, NOMBRE, FECHA_NACIMIENTO, SEXO, PAIS, CODIGO_POSTAL)
VALUES
('TOMMY@GMAIL.COM', '1234', 'THOMAS', '1990-06-04', 'H', 'ESPAÑA', '43654'),
('RUBBI@GMAIL.COM', '7789', 'RUTH', '1974-09-23', 'F', 'ESPAÑA', '08240'),
('MARC@GMAIL.COM', '2265', 'MARC', '1985-06-17', 'H', 'ESPAÑA', '09478');

INSERT INTO ESTADO_VIDEO (NOMBRE_ESTADO)
VALUES ('PUBLICO'), ('OCULTO'), ('PRIVADO');

INSERT INTO VIDEO (TITULO, DESCRIPCION, TAMAÑO_ARCHIVO, DURACION, NUMERO_REPRODUCCIONES, NUMERO_LIKES, NUMERO_DISLIKES, ESTADO, USUARIO, FECHA_PUBLICACION)
VALUES
('GATITO GRACIOSO', 'GATITO JUGANDO CON UN PAJARITO', '250.50', '00:16:15', '150', '3', '1', '1', '1', '2022-06-05 12:56:25'),
('VAYA HOSTIA', 'UN HOMBRE SE D UN GOLPE MUY FUERTE', '126.34', '00:02:36', '100', '3', '15', '1', '3', '2022-01-14 13:20:12');

INSERT INTO ETIQUETA_VIDEO (NOMBRE_ETIQUETA, ID_VIDEO, ID_USUARIO)
VALUES
('GRACIOSO', '1', '1'), ('TIERNO', '1', '1'), ('CASI SE LO COME', '1','2'),
('DOLOR', '2','2');

INSERT INTO LIKE_VIDEO (ID_USUARIO, ID_VIDEO)
VALUES ('1', '1'), ('2', '1'), ('3','1'), ('1', '2');

INSERT INTO DISLIKE_VIDEO (ID_USUARIO, ID_VIDEO)
VALUES ('1', '2'), ('2', '2');

INSERT INTO COMENTARIO (COMENTARIO, FECHA, ID_USUARIO, ID_VIDEO)
VALUES ('QUE GATITO MAS MONO', '2022-06-05', '1', '2');

INSERT INTO LIKE_COMENTARIO (ID_USUARIO, ID_COMENTARIO)
VALUES ('1', '1');

INSERT INTO PLAYLIST (ID_USUARIO, ID_ESTADO)
VALUES
('1', '1');

INSERT INTO VIDEOS_PLAYLIST (ID_PLAYLIST, ID_VIDEO)
VALUES ('1', '1'), ('1', '2');

SELECT VIDEO.TITULO, VIDEO.DESCRIPCION, LIKE_VIDEO.ID_VIDEO, LIKE_VIDEO.ID_LIKE FROM video 
INNER JOIN like_video ON VIDEO.ID_VIDEO = LIKE_VIDEO.ID_VIDEO 
WHERE LIKE_VIDEO.ID_VIDEO = 1

